[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
 "classy_szfast>=0.0.7"
]

dynamic = ["version"]
name = "classy_sz"
maintainers = [{name = "Boris Bolliet",email="bb667@cam.ac.uk"}]
description = "The class_sz code from https://github.com/CLASS-SZ"
readme = "https://github.com/CLASS-SZ/.github/blob/main/profile/README.md"

[project.urls]
Homepage = "https://github.com/CLASS-SZ"
GitHub = "https://github.com/CLASS-SZ"
